language: go
os: linux

cache:
  directories:
    - "$HOME/.cache/go-build"
    - "$HOME/gopath/pkg/mod"

env:
  global:
    - CODECLIMATE=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - GO111MODULE=on

go:
  - master
  - 1.x
  - 1.15.x
  - 1.16.x

jobs:
  allow_failures:
    - go: master

before_script:
  - make env deps-fetch
  - |
    if [[ $TRAVIS_GO_VERSION == 1.16* ]]; then
      curl -sL $CODECLIMATE > /home/travis/gopath/bin/cc-test-reporter
      chmod +x /home/travis/gopath/bin/cc-test-reporter
      cc-test-reporter before-build
    fi

script:
  - |
    if [[ $TRAVIS_GO_VERSION == 1.16* ]]; then
      make test-with-coverage
    else
      make test
    fi

after_script:
  - |
    if [[ $TRAVIS_GO_VERSION == 1.16* ]]; then
      sed -i "s|$(go list -m)/||g" c.out # https://github.com/codeclimate/test-reporter/issues/378
      cc-test-reporter after-build -t gocov -p $(go list -m) --exit-code $TRAVIS_TEST_RESULT
    fi

deploy:
  - provider: script
    cleanup: false
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION == 1.16*

notifications:
  slack:
    secure: ZTFEOXhIa/RdN/vboHLizoem30+sf8n+dDuacWtmmhHz5Z7oQ1ePi4rj5uSxm36SdPWT8X3BP4dvQ8zMDRAnGLWBdXwL3ASMx9iQaNV4yykUkfJBI6fQQQS0IlW0E7imvpCArC+k0k2BnJNekFZeINwu3D4Aj8y/uyoiElY1lsmvCyEnH4l8iwpfIULzjwzkjR0KjLU8Pw/4M1FsmHHUbhsozJhrSKWGzHfFUMvlQBUMxsu41K/HNheE3HSvJRIvJboPXxVe93yb/ZwRJFf6snurSpHl+I6R1tG2ZQLknsJ/laP7sJyS/CxKm3yTaU7/+HnR+F9zlqX2plk91W+F9gQwt8pxOzONHnhkiD9NggQL43Sh0ZRn/WZMCZSXAmgytjzRNFWBo3wUAzFX/QCRJ5okbOe7Fx6JgIP0t4xAewtP1GAxRitIh62X4M8KAx6nx/VTw5v75OC3JP8SzKk08hgzt4kxuEj1/cIqn//jyN2evOmWopHF3X2sg0ojYuCYrbSd9b5ZRHp0MmaNO+pk+IS0/+ZCH65CMASo8nvFrntNd4AM0f9ScJk6DP2NK+RtLZzYIxXpUx92aZs+cOLiKwnhvXhBK2zJHCfd9dB1gWpJRtLoGcwOTHDUeOnL0ju76IXhtVSFl/fi/4YYydkOii19Abpcw4MIkTCwnTa4xko=
