name: Continuous integration healthcheck

on:
  schedule:
    - cron: 0 6 * * * # at 06:00 every day, UTC

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Testing
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.x
          - 1.27.x

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7.0.1
        with: { fetch-depth: 0 }
      - name: Set up Go environment
        uses: actions/setup-go@v7.0.0
        with: { go-version: '${{ matrix.go }}' }

      - name: Fetch new test data
        run: |
          ./Taskfile testdata
          echo "MAINTAINER_TESTDATA_YEAR=$(date -u +%Y)" >> "$GITHUB_ENV"
      - name: Prepare and run tests
        run: make env deps-fetch test TIMEOUT=2m

  notify:
    name: Notifying
    needs: [ test ]
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request'
      && (failure() || success())

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7.0.1
        with: { fetch-depth: 0 }

      - name: Send notification
        uses: ./.github/actions/notify
        with:
          emoji: ⚙️
          channel: ${{ secrets.SLACK_WEBHOOK }}
          success: ${{ ! contains(needs.*.result, 'failure') }}
