name: Continuous integration healthcheck

on:
  schedule:
    - cron: 0 6 * * * # at 06:00 every day, UTC

  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.x
          - 1.21.x
          - 1.22.x

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.3
        with: { fetch-depth: 0 }
      - name: Set up Go environment
        uses: actions/setup-go@v5.0.0
        with: { go-version: '${{ matrix.go }}' }

      - name: Fetch new test data
        run: ./Taskfile testdata
      - name: Prepare and run tests
        run: make env deps-fetch test

  notify:
    name: Notifying
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && (failure() || success())

    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_COLOR: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
          SLACK_ICON: https://github.com/github.png?size=64
          SLACK_TITLE: '⚙️ ${{ github.repository }}: ${{ github.workflow }}'
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
