name: Tools validation

on:
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for dispatching it manually.
        type: string
        default: manual healthcheck
        required: true

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/tools.yml'
      - 'tools/**.go'
      - 'tools/go.mod'
      - 'tools/go.sum'
      - 'Makefile'

  push:
    branches: [ main ]
    paths:
      - '.github/workflows/tools.yml'
      - 'tools/**.go'
      - 'tools/go.mod'
      - 'tools/go.sum'
      - 'Makefile'
    tags: [ '!*' ]

  schedule:
    - cron: 0 7 1 * * # at 07:00 on day-of-month 1, UTC

permissions:
  contents: read

jobs:
  check:
    name: Checking
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7.0.1
        with: { fetch-depth: 0 }
      - name: Set up Go environment
        uses: actions/setup-go@v7.0.0
        with:
          go-version: 1.27.x
          cache-dependency-path: tools/go.sum
          check-latest: true

      - name: Install and check tools
        run: make tools && [ "$(find bin/linux -mindepth 2 -type f | wc -l)" = "$(cd tools && go list tool | wc -l)" ]

      - name: Check git state
        run: make tools-tidy generate git-check
      - name: Check tools
        run: make tools-check

  notify:
    name: Notifying
    needs: [ check ]
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request' && (failure() || success())

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7.0.1
        with: { fetch-depth: 0 }

      - name: Send notification
        uses: ./.github/actions/notify
        with:
          emoji: 🛠️
          channel: ${{ secrets.SLACK_WEBHOOK }}
          success: ${{ ! contains(needs.*.result, 'failure') }}
